### ISSUE TITLE
Remove yarn.lock

### ISSUE THREAD

**Issue by ganziqim** [crazymousethief/jquery-markview#1]
yarn.lock 这个文件貌似是没必要存在的？安装依赖包只要package.json就行了

**Comment by MadratJerry** [comment]
需要存在，保证依赖关系
https://yarnpkg.com/en/docs/yarn-lock

npm5 也加入了类似的 `package-lock.json`
https://docs.npmjs.com/files/package-lock.json

**Comment by ganziqim** [comment]
这个我看了下文档貌似是为了保证版本一致？应该还要再评估下有没有必要
issue由报告人来关就行

**Comment by ganziqim** [comment]
类似的包管理都有这种，是为了确保依赖包版本完全一致，我在想是不是咱们处理成跟着最新版本走比较好，而且版本的管理其实在package.json里面也能做

**Comment by MadratJerry** [comment]
必要的时候 upgrade 就好，而且现在 Github 会帮你分析你的依赖包是否存在问题，instal 时也会有 warning 提示依赖关系，这个项目去掉lock带来的收益不大

**Comment by ganziqim** [comment]
OK，如果确定这东西不会导致版本更新不及时就好，咱们团队项目体量小，尽量保持能跟依赖库同步保持更新

**Comment by ganziqim** [comment]
Done.
